# Generated by Django 3.2.7 on 2021-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_hotel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=25)),
                ('phone_number', models.BigIntegerField()),
                ('date', models.DateField()),
                ('number_of_nights', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=300)),
                ('number_of_guests', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=300)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
