# Generated by Django 3.2.7 on 2021-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210924_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='notes',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='detail',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
