# Generated by Django 3.2.7 on 2021-09-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_detail_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
    ]
