# Generated by Django 3.2.7 on 2021-09-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_detail_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
    ]
