# Generated by Django 3.2.7 on 2021-09-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210924_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='first_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='last_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='notes',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
