# Generated by Django 3.2.7 on 2021-09-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210924_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AddField(
            model_name='detail',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hotel'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='notes',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
