# Generated by Django 3.2.7 on 2021-09-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210924_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='hotel',
        ),
    ]
