# Generated by Django 3.2.7 on 2021-09-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_detail_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='HotelDetail',
        ),
    ]
