# Generated by Django 3.2.7 on 2021-09-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_detail_hoteldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetail',
            name='password',
        ),
    ]
