# Generated by Django 3.2.7 on 2021-09-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_hoteldetail_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='date',
            new_name='date_reserve',
        ),
    ]
