# Generated by Django 3.2.7 on 2021-09-25 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_date_hoteldetail_date_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetail',
            name='city',
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hotel'),
        ),
    ]
