# Generated by Django 3.2.7 on 2021-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210925_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetail',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
