# Generated by Django 3.2.7 on 2021-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
