# Generated by Django 3.2.7 on 2021-09-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetail',
            name='hotel',
        ),
    ]
