# Generated by Django 3.2.7 on 2021-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_hoteldetail_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetail',
            name='na',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
