# Generated by Django 3.2.7 on 2021-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210926_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
