# Generated by Django 3.2.7 on 2021-09-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_hotel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, null=True)),
                ('last_name', models.CharField(max_length=75, null=True)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', models.BigIntegerField(default=0, null=True)),
                ('date_reserve', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='HotelDetail',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='quantity',
        ),
    ]
